### ISSUE TITLE
Feature Request: reCaptcha integration

### ISSUE THREAD

**Issue by davemoz** [aamodtgroup/frontity-contact-form-7#17]
I have the reCaptcha v3 integration turned on in my WP installation with CF7. When I installed this package to use with my Frontity front-end, I noticed everything worked great except the reCaptcha was excluded/missing. Are there any plans to add support for this integration? I see there is Akismet integration, though it would be helpful to be able to continue using reCaptcha for spam-blocking. Thanks!

**Comment by kasperaamodt** [comment]
I will look into this

**Comment by garridinsi** [comment]
Hi! I report that I've also tried with hCaptcha instead of reCaptcha, and is not appearing. I write this to take that situation into account. Thanks!

**Comment by kasperaamodt** [comment]
Hello @davemoz & @garridinsi,

Frontity does not execute the ReCaptcha scripts from WP, because of the reasons in their [documentation](https://api.frontity.org/frontity-packages/features-packages/html2react#script). So the ReCaptcha script never reaches the Frontity frontend. There isn't really anything I can do about this, as it would require changes either in the CF7 plugin, or in the Html2React package from Frontity.

An alternative would be to use a npm package to enable ReCaptcha on your frontend.
